
-- Users table for RBAC
CREATE TABLE IF NOT EXISTS USERS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ORGID VARCHAR(32) NOT NULL,
  USERNAME VARCHAR(64) NOT NULL UNIQUE,
  PASSWORD_HASH VARCHAR(255) NOT NULL,
  ROLE ENUM('admin', 'uploader', 'viewer') DEFAULT 'viewer',
  ACTIVE BOOLEAN DEFAULT TRUE
);

-- Metadata schema templates per repository
CREATE TABLE IF NOT EXISTS METADATA_SCHEMA (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ORGID VARCHAR(32) NOT NULL,
  CONTREP_ID VARCHAR(32) NOT NULL,
  FIELD_NAME VARCHAR(64) NOT NULL,
  FIELD_TYPE VARCHAR(32) NOT NULL,
  REQUIRED BOOLEAN DEFAULT FALSE,
  UNIQUE (ORGID, CONTREP_ID, FIELD_NAME)
);

-- ArchiveLink fields added to DOCUMENTS_<ORGID>_<REPOID> dynamically
-- e.g., SAP_DOC_TYPE, ARCHIVELINK_ID
-- Handled in backend auto-creator
