
-- Add Legal Hold flag to documents (to be applied dynamically per repo table)
-- Backend will assume DOCUMENTS_<ORGID>_<REPOID> has LEGAL_HOLD BOOLEAN DEFAULT FALSE

-- Audit Trail Table
CREATE TABLE IF NOT EXISTS AUDIT_TRAIL (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ORGID VARCHAR(32),
  CONTREP_ID VARCHAR(32),
  DOC_NAME VARCHAR(254),
  ACTION VARCHAR(64),
  USERNAME VARCHAR(64),
  TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
  DETAILS TEXT
);
