
-- Migration staging table (optional)
CREATE TABLE IF NOT EXISTS MIGRATION_STAGING (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ORGID VARCHAR(32),
  CONTREP_ID VARCHAR(32),
  SOURCE_TYPE VARCHAR(32), -- e.g. 'MAXDB', 'OPENTEXT'
  DOC_NAME VARCHAR(254),
  METADATA JSON,
  BINARY_DATA LONGBLOB,
  MIGRATED BOOLEAN DEFAULT FALSE,
  MIGRATED_AT TIMESTAMP NULL
);
