
-- Retention Policies Table
CREATE TABLE IF NOT EXISTS RETENTION_RULES (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ORGID VARCHAR(32) NOT NULL,
  CONTREP_ID VARCHAR(32) NOT NULL,
  DOC_TYPE VARCHAR(64) DEFAULT NULL,
  RETENTION_YEARS INT DEFAULT 7,
  DELETE_AFTER_RETENTION BOOLEAN DEFAULT FALSE,
  ACTIVE BOOLEAN DEFAULT TRUE,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (ORGID, CONTREP_ID, DOC_TYPE)
);
